In [2]:
import pandas as pd

In [3]:
df_produtos = pd.read_csv('produtos.csv')

In [4]:
df_produtos

       Produto   Categoria  Preço  Quantidade  Data_Venda
0       Camisa      Roupas   50.0          10  2023-01-01
1        Calça      Roupas  100.0          15  2023-01-02
2         Saia      Roupas   80.0          20  2023-01-03
3     Camiseta      Roupas   45.0          30  2023-01-04
4      Jaqueta      Roupas  120.0           5  2023-01-05
5      Vestido      Roupas   90.0          12  2023-01-06
6      Bermuda      Roupas   60.0          18  2023-01-07
7       Sapato    Calçados  150.0           7  2023-01-08
8     Sandália    Calçados   70.0          25  2023-01-09
9        Tênis    Calçados  200.0           8  2023-01-10
10       Botas    Calçados  180.0           6  2023-01-11
11     Mochila  Acessórios   70.0          15  2023-01-12
12       Cinto  Acessórios   40.0          22  2023-01-13
13      Óculos  Acessórios  120.0          10  2023-01-14
14     Relógio  Acessórios  250.0           4  2023-01-15
15      Brinco  Acessórios   35.0          30  2023-01-16
16       Blusa      Roupas   55.0          14  2023-01-17
17      Shorts      Roupas   65.0          19  2023-01-18
18      Suéter      Roupas   95.0           9  2023-01-19
19  Saia longa      Roupas   75.0          11  2023-01-20

In [37]:
#Desempenho por categoria
vendas_categorias = df_produtos.groupby('Categoria')['Quantidade'].sum().reset_index()

In [38]:
vendas_categorias

    Categoria  Quantidade
0  Acessórios          81
1    Calçados          46
2      Roupas         163

In [49]:
#Produto mais vendido
produto_mais_vendido = df_produtos.groupby('Produto')['Quantidade'].sum().idxmax()

In [50]:
produto_mais_vendido

'Brinco'

In [47]:
#Total de unidades vendidas
total_unidades = df_produtos.groupby('Produto')['Quantidade'].max()

In [48]:
total_unidades

Produto
Bermuda       18
Blusa         14
Botas          6
Brinco        30
Calça         15
Camisa        10
Camiseta      30
Cinto         22
Jaqueta        5
Mochila       15
Relógio        4
Saia          20
Saia longa    11
Sandália      25
Sapato         7
Shorts        19
Suéter         9
Tênis          8
Vestido       12
Óculos        10
Name: Quantidade, dtype: int64

In [52]:
#Correlação UNIDADE X PREÇO
correlacao = df_produtos['Quantidade'].corr(df_produtos['Preço'])

In [53]:
correlacao

np.float64(-0.7228821786680254)